Repository codestates-seb/seb44_main_025, pull requests merged in 2023-07, with the labels that each got.

#40 Feat: fe/buttons
  client/src/components/Buttons/Buttons.tsx
  client/src/components/buttons.tsx
  client/src/custom.d.ts
  client/src/icons/icon_right.svg
Labels: FE

#41 Feat fe/concertpreview
  client/.eslintrc.json
  client/public/우리사랑이대로.jpeg
  client/src/App.tsx
  client/src/components/concertpreview.tsx
  client/src/index.css
Labels: FE, Feat

#42 Feat fe/tabs
  client/src/components/Tabs/Tabs.tsx
  client/src/components/tabs.tsx
Labels: FE

#43 Feat: fe/headers
  client/.eslintrc.json
  client/src/components/Header/Header.styled.tsx
  client/src/components/Header/HeaderLogoST.tsx
  client/src/components/Header/HeaderOnlyP.tsx
  client/src/components/Header/HeaderOnlyPrevious.tsx
  client/src/components/Header/HeaderPST.tsx
  client/src/icons/PreviousIcon.tsx
  client/src/icons/SearchIcon.tsx
  client/src/icons/TicketIcon.tsx
Labels: FE, Feat

#45 Feat fe/artistpreview
  client/src/App.tsx
  client/src/components/artist.tsx
  client/src/components/artistcontainer.tsx
  client/src/components/artistmain.tsx
  client/src/components/artistreview.tsx
  client/src/components/artistreviewcontainer.tsx
  client/src/index.css
Labels: FE, Feat

#47 Feat fe/review
  client/src/App.tsx
  client/src/components/artist/artist.tsx
  client/src/components/artist/artistcontainer.tsx
  client/src/components/artist/artistmain.tsx
  client/src/components/artist/artistreview.tsx
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/concertpreview/concertpreview.tsx
  client/src/components/review/review.tsx
Labels: FE, Feat

#49 Feat fe/input
  client/src/components/Inputs/Inputs.tsx
  client/src/icons/icon_close.svg
  client/src/icons/icon_search.svg
Labels: FE, Feat

#50 Feat fe/mypage
  client/src/App.tsx
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/concertpreview/concertpreview.tsx
  client/src/components/footer.tsx
  client/src/components/pagination.tsx
  client/src/components/review/review.tsx
  client/src/icons/EditIcon.tsx
  client/src/index.css
  client/src/pages/mypage.tsx
Labels: FE, Feat

#51 Fix fe/buttons
  client/src/components/Buttons/Buttons.tsx
Labels: FE

#55 Feat fe/navbar
  client/src/components/Navs/Nav.styled.tsx
  client/src/components/Navs/NavLogin.tsx
  client/src/components/Navs/NavMypage.tsx
  client/src/index.css
Labels: FE, Feat

#57 Feat fe/navbar
  client/src/components/Navs/Nav.styled.tsx
  client/src/components/Navs/NavLogin.tsx
  client/src/components/Navs/NavMypage.tsx
Labels: FE, Feat

#64 Feat be/member
  .idea/uiDesigner.xml
  BE/MainProject/src/main/java/com/codestates/artist/Artist.java
  BE/MainProject/src/main/java/com/codestates/artist/ArtistController.java
  BE/MainProject/src/main/java/com/codestates/artist/ArtistMapper.java
  BE/MainProject/src/main/java/com/codestates/artist/ArtistRepository.java
  BE/MainProject/src/main/java/com/codestates/artist/ArtistService.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistDto.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistDtoToArtist.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistPageResponseDto.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistResponseDto.java
  BE/MainProject/src/main/java/com/codestates/category/Category.java
  BE/MainProject/src/main/java/com/codestates/category/CategoryController.java
  BE/MainProject/src/main/java/com/codestates/category/CategoryMapper.java
  BE/MainProject/src/main/java/com/codestates/category/CategoryRepository.java
  BE/MainProject/src/main/java/com/codestates/category/CategoryService.java
  BE/MainProject/src/main/java/com/codestates/category/dto/CategoryPostDto.java
  BE/MainProject/src/main/java/com/codestates/global/PageInfo.java
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/member/Member.java
  BE/MainProject/src/main/java/com/codestates/member/MemberController.java
  BE/MainProject/src/main/java/com/codestates/member/MemberMapper.java
  BE/MainProject/src/main/java/com/codestates/member/MemberRepository.java
  BE/MainProject/src/main/java/com/codestates/member/MemberService.java
  BE/MainProject/src/main/java/com/codestates/member/dto/MemberPatchDto.java
  BE/MainProject/src/main/java/com/codestates/member/dto/MemberPostDto.java
  BE/MainProject/src/main/java/com/codestates/member/dto/MemberResponseDto.java
  BE/MainProject/src/main/java/com/codestates/snslink/SnsLink.java
  BE/MainProject/src/main/resources/application.yml
  BE/MainProject/src/main/resources/db/h2/schema.sql
  client/.estlintrc.json
  client/src/components/buttons.tsx
  client/src/components/tabs.tsx
Labels: BE, Feat

#65 Feat be/performance
  BE/MainProject/build.gradle
  BE/MainProject/src/main/java/com/codestates/content/entity/Content.java
  BE/MainProject/src/main/java/com/codestates/global/response/SingleResponseDto.java
  BE/MainProject/src/main/java/com/codestates/image/ImageUploadService.java
  BE/MainProject/src/main/java/com/codestates/performance/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceDto.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/mapper/PerformanceMapper.java
  BE/MainProject/src/main/java/com/codestates/performance/registory/PerformanceRegistory.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
  BE/MainProject/src/main/resources/application.properties
  BE/MainProject/src/main/resources/application.yml
  BE/MainProject/src/test/java/com/codestates/performance/PerformanceControllerTest.java
Labels: BE, Feat

#71 feat:아티스트 등록페이지
  client/src/App.tsx
  client/src/pages/artistpage.tsx
  client/src/pages/artistregistpage.tsx
  client/src/pages/mypage.tsx
Labels: FE, Feat

#74 feat: 회원탈퇴페이지
  client/src/App.tsx
  client/src/pages/artistregistpage.tsx
  client/src/pages/cancelpage.tsx
  client/src/pages/editmypage.tsx
Labels: FE, Feat

#76 Refactor fe/input
  client/package-lock.json
  client/package.json
  client/src/components/Inputs/Inputs.tsx
Labels: FE

#75 feat: notfound
  client/src/App.tsx
  client/src/components/artist/artist.tsx
  client/src/components/artist/artistcontainer.tsx
  client/src/components/artist/artistmain.tsx
  client/src/components/artist/artistreview.tsx
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/concertpreview/concertpreview.tsx
  client/src/components/footer.tsx
  client/src/components/review/review.tsx
  client/src/custom.d.ts
  client/src/images/우리사랑이대로.jpeg
  client/src/index.tsx
  client/src/pages/artistpage.tsx
  client/src/pages/artistregistpage.tsx
  client/src/pages/cancelpage.tsx
  client/src/pages/editmypage.tsx
  client/src/pages/mypage.tsx
  client/src/pages/notfondpage.tsx
Labels: FE, Feat

#78 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/artist/Artist.java
  BE/MainProject/src/main/java/com/codestates/category/Category.java
  BE/MainProject/src/main/java/com/codestates/global/dto/MultiResponseDto.java
  BE/MainProject/src/main/java/com/codestates/global/dto/SingleResponseDto.java
  BE/MainProject/src/main/java/com/codestates/image/ImageUploadService.java
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceDto.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/PerformanceArtist.java
  BE/MainProject/src/main/java/com/codestates/performance/mapper/PerformanceMapper.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#79 Feat fe/editor
  client/package-lock.json
  client/package.json
  client/src/components/Inputs/Editor/Editor.style.tsx
  client/src/components/Inputs/Editor/Editor.tsx
  client/src/components/Inputs/Editor/EditorStore.tsx
  client/src/components/Inputs/Editor/EditorViewer.tsx
  client/src/index.tsx
  client/src/pages/PerformanceInfo.tsx
  client/src/pages/PerformanceRegister.tsx
Labels: FE, Feat

#84 Feat fe/signpages
  client/package-lock.json
  client/package.json
  client/src/components/Sign/PageMovement.tsx
  client/src/index.tsx
  client/src/pages/SignUpIn/Sign.styled.tsx
  client/src/pages/SignUpIn/SignInPage.tsx
  client/src/pages/SignUpIn/SignUpPage.tsx
  client/src/service-worker.js
  client/src/utils/Cookie.tsx
  client/src/utils/RegExp.tsx
  client/src/zustand/Dupl.stores.tsx
  client/src/zustand/Duplication.tsx
Labels: FE, Feat

#91 Rename fe/파일명 컨벤션 통일
  client/src/API/MainAPI.tsx
  client/src/components/artistpreview/ArtistPreview.tsx
  client/src/components/buttons/Buttons.tsx
  client/src/components/buttons/MainPageButton.tsx
  client/src/components/carousel/CarouselLogic.tsx
  client/src/components/carousel/CarouselSlide.tsx
  client/src/components/concert-preview/ConcertPreview.tsx
  client/src/components/footer/Footer.tsx
  client/src/components/header/Header.styled.tsx
  client/src/components/header/HeaderLogoST.tsx
  client/src/components/header/HeaderOnlyP.tsx
  client/src/components/header/HeaderPST.tsx
  client/src/components/inputs/Inputs.tsx
  client/src/components/inputs/editor/Editor.style.tsx
  client/src/components/inputs/editor/Editor.tsx
  client/src/components/inputs/editor/EditorStore.tsx
  client/src/components/inputs/editor/EditorViewer.tsx
  client/src/components/modal/NoTicket.tsx
  client/src/components/modal/Reservation.tsx
  client/src/components/modal/Ticket.tsx
  client/src/components/navs/Nav.styled.tsx
  client/src/components/navs/NavLogin.tsx
  client/src/components/navs/NavMypage.tsx
  client/src/components/pagination/Pagination.tsx
  client/src/components/review/Review.tsx
  client/src/components/sign/PageMovement.tsx
  client/src/components/slogan/Slogan.tsx
  client/src/components/tabs/Tabs.tsx
  client/src/index.tsx
  client/src/pages/Artist.tsx
  client/src/pages/ArtistList.tsx
  client/src/pages/ArtistRegister.tsx
  client/src/pages/Cancel.tsx
  client/src/pages/EditMyPage.tsx
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/PerformanceInfo.tsx
  client/src/pages/PerformanceList.tsx
  client/src/pages/sign/Sign.styled.ts
  client/src/pages/sign/SignIn.tsx
  client/src/pages/sign/SignUp.tsx
Labels: FE

#93 Feat fe/performance
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/inputs/StyledInputs.tsx
  client/src/pages/PerformanceRegister.tsx
  client/src/pages/performance-register/PerformanceRegister.style.ts
  client/src/pages/performance-register/PerformanceRegister.tsx
Labels: FE, Feat

#88 feat:Reservation의controller,service기능들 mapper이용해 수정, status 수정
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/dto/ReviewDto.java
  BE/MainProject/src/main/java/com/codestates/performancereview/entity/Review.java
  BE/MainProject/src/main/java/com/codestates/performancereview/mapper/ReviewMapper.java
  BE/MainProject/src/main/java/com/codestates/performancereview/repository/ReviewRepository.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
  BE/MainProject/src/main/java/com/codestates/reservation/entity/Reservation.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#94 Feat fe/artistregistpage
  client/artistpage.json
  client/public/dummy/artistpage.json
  client/public/dummy/performancelist.json
  client/public/dummy/review.json
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/concert-preview/ConcertPreview.tsx
  client/src/components/review/Review.tsx
  client/src/index.tsx
  client/src/pages/Artist.tsx
  client/src/pages/ArtistRegister.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/PerformanceInfo.tsx
  client/src/pages/PerformanceList.tsx
  client/src/zustand/artistpage.stores.tsx
  client/src/zustand/mainapi.tsx
Labels: FE, Feat

#95 Feat fe/input 컴포넌트 통합 및 사용성 개선
  client/src/components/inputs/Inputs.tsx
  client/src/components/inputs/StyledInputs.tsx
  client/src/components/inputs/Styled_Inputs.ts
  client/src/components/inputs/Theme.ts
  client/src/components/row/Row.tsx
  client/src/components/text/Theme.ts
  client/src/pages/ArtistRegister.tsx
  client/src/pages/Cancel.tsx
  client/src/pages/EditMyPage.tsx
  client/src/pages/Main.tsx
  client/src/pages/performance-register/PerformanceRegister.tsx
Labels: FE, Feat

#92 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/artist/Artist.java
  BE/MainProject/src/main/java/com/codestates/category/Category.java
  BE/MainProject/src/main/java/com/codestates/content/entity/Content.java
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceArtistDto.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceDto.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/PerformanceArtist.java
  BE/MainProject/src/main/java/com/codestates/performance/mapper/PerformanceMapper.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
  BE/MainProject/src/test/java/com/codestates/performance/PerformanceControllerTest.java
Labels: BE, Feat

#97 Feat fe/fixmypage
  client/artistpage.json
  client/mypage.json
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/concert-preview/ConcertPreview.tsx
  client/src/components/review/Review.tsx
  client/src/pages/Artist.tsx
  client/src/pages/ArtistRegister.tsx
  client/src/pages/EditMyPage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/PerformanceInfo.tsx
  client/src/zustand/artistpage.stores.tsx
  client/src/zustand/mypage.stores.tsx
Labels: FE, Feat

#99 Feat fe/mainpage
  client/src/components/artist/ArtistHome.styled.ts
  client/src/components/artist/ArtistHome.tsx
  client/src/components/artist/artistmain.tsx
  client/src/components/buttons/HomePageButton.styled.ts
  client/src/components/buttons/HomePageButton.tsx
  client/src/components/buttons/MainPageButton.tsx
  client/src/components/carousel/CarouselLogic.styled.ts
  client/src/components/carousel/CarouselLogic.tsx
  client/src/components/carousel/CarouselSlide.styled.ts
  client/src/components/carousel/CarouselSlide.tsx
  client/src/components/header/Header.styled.ts
  client/src/components/header/Header.tsx
  client/src/components/header/HeaderLogoST.tsx
  client/src/components/header/HeaderOnlyP.tsx
  client/src/components/header/HeaderPST.tsx
  client/src/components/nav/Navbar.styled.ts
  client/src/components/nav/Navbar.tsx
  client/src/components/navs/NavLogin.tsx
  client/src/components/navs/NavMypage.tsx
  client/src/components/sign/PageMovement.styled.ts
  client/src/components/sign/PageMovement.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/Artist.tsx
  client/src/pages/ArtistList.tsx
  client/src/pages/ArtistRegister.tsx
  client/src/pages/Cancel.tsx
  client/src/pages/EditMyPage.tsx
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/home/Home.styled.ts
  client/src/pages/home/Home.tsx
  client/src/pages/performance-info/PerformanceInfo.tsx
  client/src/pages/performance-list/PerformanceList.tsx
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/review/ReviewRegister.tsx
  client/src/pages/sign/Sign.styled.ts
  client/src/pages/sign/SignIn.tsx
  client/src/pages/sign/SignUp.tsx
  client/src/utils/Theme.ts
  client/src/zustand/Dupl.stores.tsx
  client/src/zustand/Duplication.tsx
Labels: FE, Feat

#104 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceArtistDto.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/mapper/PerformanceMapper.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/Performancecomment.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/controller/PerformanceCommentController.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/dto/PerformanceCommentDto.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/entity/PerformanceComment.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/mapper/PerformanceCommentMapper.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/repository/PerformanceCommentRepository.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/service/PerformanceCommentService.java
  BE/MainProject/src/main/java/com/codestates/performancecomment/service/PerformanceCommentServiceImpl.java
Labels: BE, Feat

#107 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceArtistDto.java
  BE/MainProject/src/main/java/com/codestates/performance/mapper/PerformanceMapper.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
  BE/MainProject/src/main/resources/application.yml
Labels: BE, Feat

#109 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/global/dto/MultiResponseDto.java
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#111 Feat fe/api
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/nav/Navbar.tsx
  client/src/pages/Artist.tsx
  client/src/pages/ArtistList.tsx
  client/src/pages/ArtistRegister.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/performance-info/PerformanceInfo.tsx
  client/src/pages/performance-list/PerformanceList.tsx
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/review/ReviewRegister.tsx
  client/src/pages/sign/SignIn.tsx
  client/src/pages/sign/SignUp.tsx
Labels: FE, Feat

#112 Feat fe/mainpage
  client/public/Images/피아노.webp
  client/public/dummy/main.json
  client/public/dummy/main_artistlist.json
  client/public/dummy/main_perfomancelist.json
  client/src/components/artist/ArtistHome.styled.ts
  client/src/components/artist/ArtistHome.tsx
  client/src/components/buttons/HomePageButton.styled.ts
  client/src/components/carousel/CarouselLogic.tsx
  client/src/components/carousel/CarouselSlide.tsx
  client/src/model/Artist.ts
  client/src/model/Performance.ts
  client/src/pages/ArtistList.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/sign/Sign.styled.ts
  client/src/pages/sign/SignIn.tsx
  client/src/pages/sign/SignUp.tsx
  client/src/utils/SlideUp.tsx
  client/src/zustand/homepage.stores.tsx
  client/src/zustand/mainapi.tsx
  client/src/zustand/userloginInfo.stores.tsx
Labels: FE

#119 Feat be/member
  BE/MainProject/src/main/java/com/codestates/artist/Artist.java
  BE/MainProject/src/main/java/com/codestates/artist/ArtistController.java
  BE/MainProject/src/main/java/com/codestates/artist/ArtistService.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistDto.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistName.java
  BE/MainProject/src/main/java/com/codestates/artist/dto/ArtistResponseDto.java
  BE/MainProject/src/main/java/com/codestates/artist/mapper/ArtistDtoToArtist.java
  BE/MainProject/src/main/java/com/codestates/artist/mapper/ArtistMapper.java
  BE/MainProject/src/main/java/com/codestates/category/Category.java
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/global/security/jwt/config/SecurityConfiguration.java
  BE/MainProject/src/main/java/com/codestates/global/security/jwt/dto/LoginResponseDto.java
  BE/MainProject/src/main/java/com/codestates/global/security/jwt/filter/JwtAuthenticationFilter.java
  BE/MainProject/src/main/java/com/codestates/member/Member.java
  BE/MainProject/src/main/java/com/codestates/member/MemberController.java
  BE/MainProject/src/main/java/com/codestates/member/MemberMapper.java
  BE/MainProject/src/main/java/com/codestates/member/MemberRepository.java
  BE/MainProject/src/main/java/com/codestates/member/MemberService.java
  BE/MainProject/src/main/java/com/codestates/member/dto/MemberPatchDto.java
  BE/MainProject/src/main/java/com/codestates/member/dto/MemberResponseDto.java
  BE/MainProject/src/main/java/com/codestates/member/dto/duplicate/MemberEmail.java
  BE/MainProject/src/main/java/com/codestates/member/dto/duplicate/MemberNickname.java
  BE/MainProject/src/main/java/com/codestates/member/dto/duplicate/MemberPassword.java
  BE/MainProject/src/test/java/com/codestates/performance/PerformanceControllerTest.java
Labels: bug, BE, Feat

#116 Feat fe/components
  client/.env
  client/.gitignore
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/buttons/Buttons.style.ts
  client/src/components/buttons/Buttons.tsx
  client/src/components/inputs/Inputs.style.ts
  client/src/components/inputs/Inputs.tsx
  client/src/components/inputs/Theme.ts
  client/src/components/nav/Navbar.tsx
  client/src/pages/ArtistList.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/PerformanceInfo.tsx
  client/src/pages/performance-info/PerformanceInfo.style.ts
  client/src/pages/performance-info/PerformanceInfo.tsx
  client/src/pages/performance-list/PerformanceList.tsx
  client/src/pages/performance-register/PerformanceRegister.style.ts
  client/src/pages/performance-register/PerformanceRegister.tsx
Labels: FE, Feat

#124 Feat be/performance review / reviewTitle 추가
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/dto/ReviewDto.java
  BE/MainProject/src/main/java/com/codestates/performancereview/entity/Review.java
  BE/MainProject/src/main/java/com/codestates/performancereview/mapper/ReviewMapper.java
  BE/MainProject/src/main/java/com/codestates/performancereview/mapper/ReviewMapperImpl.java
  BE/MainProject/src/main/java/com/codestates/performancereview/repository/ReviewRepository.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#126 Feat fe/fixartistpage
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/concert-preview/ConcertPreview.tsx
  client/src/components/footer/Footer.tsx
  client/src/icons/EditIcon.tsx
  client/src/index.tsx
  client/src/model/Artist.ts
  client/src/model/Member.ts
  client/src/model/Performance.ts
  client/src/pages/Artist.tsx
  client/src/pages/EditMyPage.tsx
  client/src/pages/artist-register/ArtistRegister.style.ts
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/artist/Artist.style.ts
  client/src/pages/artist/Artist.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/mypage/MyPage.style.ts
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/performance-list/PerformanceList.tsx
  client/src/pages/sign/SignUp.tsx
  client/src/utils/RegExp.tsx
  client/src/zustand/artistpage.stores.tsx
  client/src/zustand/mypage.stores.tsx
Labels: FE, Feat

#125 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/content/entity/Content.java
  BE/MainProject/src/main/java/com/codestates/image/ImageUploadService.java
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceArtistDto.java
  BE/MainProject/src/main/java/com/codestates/performance/dto/PerformanceDto.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/mapper/PerformanceMapper.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#130 Feat: performance 카테고리별 리스트 조회에서 공연상태 검색 가능하도록 수정
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#136 Feat fe/api
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/artistpreview/ArtistPreview.tsx
  client/src/components/inputs/Inputs.tsx
  client/src/components/modal/Reservation.tsx
  client/src/index.tsx
  client/src/model/Artist.ts
  client/src/pages/ArtistList.tsx
  client/src/pages/artist-list/ArtistList.style.ts
  client/src/pages/artist-list/ArtistList.tsx
  client/src/pages/performance-info/PerformanceInfo.tsx
  client/src/pages/performance-list/PerformanceList.style.ts
  client/src/pages/performance-list/PerformanceList.tsx
  client/src/pages/performance-register/PerformanceRegister.tsx
Labels: FE, Feat

#138 Feat: performance 해당 아티스트의 공연 목록 검색 기능 추가
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/PerformanceArtist.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#132 feat: 예약 생성부분 추가 구현
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/dto/ReviewDto.java
  BE/MainProject/src/main/java/com/codestates/performancereview/entity/Review.java
  BE/MainProject/src/main/java/com/codestates/performancereview/mapper/ReviewMapperImpl.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
  BE/MainProject/src/main/java/com/codestates/reservation/dto/ReservationDto.java
Labels: BE, Feat

#141 feat:Reservation 수정
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
Labels: BE, Feat

#142 feat:공연에 대한 review url 변경 및 nickname, date 추가 기능 구현
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/dto/ReviewDto.java
  BE/MainProject/src/main/java/com/codestates/performancereview/entity/Review.java
  BE/MainProject/src/main/java/com/codestates/performancereview/mapper/ReviewMapperImpl.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
Labels: BE, Feat

#145 Refactor:reservation url 수정
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
Labels: BE, Feat

#146 Feat:reservation postmapping 수정
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
Labels: BE, Feat

#147 Feat:reservation date 타입 변경
  BE/MainProject/src/main/java/com/codestates/performancereview/entity/Review.java
  BE/MainProject/src/main/java/com/codestates/reservation/dto/ReservationDto.java
  BE/MainProject/src/main/java/com/codestates/reservation/entity/Reservation.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#149 feat:reservation date 관련 재수정
  BE/MainProject/src/main/java/com/codestates/reservation/dto/ReservationDto.java
  BE/MainProject/src/main/java/com/codestates/reservation/entity/Reservation.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#151 Fix fe/postcode
  client/src/components/postcode/Postcode.js
Labels: bug, FE

#153 Fix: 아티스트 수정 리펙토링
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/index.tsx
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist/Artist.tsx
  client/src/zustand/artist.stores.tsx
Labels: FE, Feat

#154 feat:Review 수정 및 ReservationService 트랜잭션 적용
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/mapper/ReservationMapper.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#155 Fix:review import 부분 수정
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/mapper/ReviewMapperImpl.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
Labels: BE, Feat

#159 Feat fe/refactor
  client/src/api/useFetch.ts
  client/src/components/artist/ArtistHome.styled.ts
  client/src/components/artist/ArtistHome.tsx
  client/src/components/buttons/HomePageButton.styled.ts
  client/src/components/carousel/CarouselLogic.styled.ts
  client/src/components/carousel/CarouselLogic.tsx
  client/src/components/carousel/CarouselSlide.styled.ts
  client/src/components/header/Header.styled.ts
  client/src/components/nav/Navbar.styled.ts
  client/src/components/oauth/OAuth.tsx
  client/src/components/slogan/Slogan.styled.ts
  client/src/components/slogan/Slogan.tsx
  client/src/pages/artist-list/ArtistList.tsx
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/cancel/Cancel.tsx
  client/src/pages/home/Home.styled.ts
  client/src/pages/home/Home.tsx
  client/src/pages/mypage/EditMyPage.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/performance-info/PerformanceInfo.tsx
  client/src/pages/performance-list/PerformanceList.tsx
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/sign/Sign.styled.ts
  client/src/pages/sign/SignIn.tsx
  client/src/pages/sign/SignUp.tsx
  client/src/theme/common/SlideUp.ts
  client/src/utils/Cookie.ts
  client/src/utils/MediaSize.ts
  client/src/utils/RegExp.ts
  client/src/zustand/artist.stores.ts
  client/src/zustand/homepage.stores.ts
  client/src/zustand/homepage.stores.tsx
  client/src/zustand/userInfo.stores.ts
  client/src/zustand/userloginInfo.stores.tsx
Labels: FE, Feat

#160 Feat fe/editmypage
  client/.estlintrc.json
  client/artistpage.json
  client/mypage.json
  client/public/dummy/artistpage.json
  client/public/dummy/member.json
  client/public/dummy/performancelist.json
  client/public/dummy/review.json
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/footer/Footer.tsx
  client/src/components/header/Header.styled.ts
  client/src/components/header/Header.tsx
  client/src/components/inputs/Inputs.tsx
  client/src/custom.d.ts
  client/src/icons/EZ to play_5.svg
  client/src/icons/EZ to play_8.svg
  client/src/images/우리사랑이대로.jpeg
  client/src/index.tsx
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist-register/ArtistRegister.style.ts
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/artist/Artist.style.ts
  client/src/pages/artist/Artist.tsx
  client/src/pages/mypage/EditMyPage.style.ts
  client/src/pages/mypage/EditMyPage.tsx
  client/src/pages/mypage/MyPage.style.ts
  client/src/pages/mypage/MyPage.tsx
  client/src/utils/RegExp.ts
Labels: FE, Feat

#161 feat:ReservationDto 타입 수정, review jwt 적용
  BE/MainProject/src/main/java/com/codestates/global/exception/ExceptionCode.java
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/dto/ReviewDto.java
  BE/MainProject/src/main/java/com/codestates/performancereview/entity/Review.java
  BE/MainProject/src/main/java/com/codestates/performancereview/repository/ReviewRepository.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/dto/ReservationDto.java
Labels: BE, Feat

#162 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
Labels: BE

#163 feat: 티켓모달 구현
  client/src/components/artistpreview/ArtistPreview.tsx
  client/src/components/concert-preview/ConcertPreview.tsx
  client/src/components/header/Header.tsx
  client/src/components/modal/NoTicket.tsx
  client/src/components/modal/Ticket.style.ts
  client/src/components/modal/Ticket.tsx
  client/src/images/공연찾기.jpg
  client/src/images/예약한 공연이 없을때.jpeg
  client/src/model/Member.ts
  client/src/pages/NotFound.tsx
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist/Artist.tsx
  client/src/pages/mypage/EditMyPage.tsx
Labels: FE, Feat

#165 Feat fe/style
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/buttons/Buttons.style.ts
  client/src/components/inputs/editor/Editor.style.tsx
  client/src/components/review/Review.tsx
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/performance-list/PerformanceList.style.ts
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/performance/performance-edit/PerformanceEdit.tsx
  client/src/pages/performance/performance-info/PerformanceInfo.tsx
  client/src/pages/review-register/ReviewRegister.style.ts
  client/src/pages/review-register/ReviewRegister.tsx
Labels: FE, Feat

#167 Feat fe/slogan
  client/public/Images/2b3fad00c203b730.png
  client/public/Images/600bb2ac964c4a46.png
  client/public/Images/7955f4c5e4d540fb.png
  client/public/Images/dd28119305b114d0.png
  client/public/Images/슬로건.png
  client/src/components/slogan/Slogan.styled.ts
  client/src/components/slogan/Slogan.tsx
  client/src/pages/home/Home.tsx
Labels: FE, Feat

#169 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/performance/controller/PerformanceController.java
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/repository/PerformanceRepository.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceService.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#170 Feat fe/fixcode
  client/public/Images/2b3fad00c203b730.png
  client/public/Images/600bb2ac964c4a46.png
  client/public/Images/슬로건.png
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/artist/artistreviewcontainer.tsx
  client/src/components/inputs/editor/Editor.tsx
  client/src/components/modal/Ticket.style.ts
  client/src/components/modal/Ticket.tsx
  client/src/components/review/Review.tsx
  client/src/components/slogan/Slogan.tsx
  client/src/images/공연찾기.jpg
  client/src/images/이투플아티스트슬로건.png
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist-register/ArtistRegister.style.ts
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/artist/Artist.style.ts
  client/src/pages/artist/Artist.tsx
  client/src/pages/mypage/EditMyPage.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/performance/performance-edit/PerformanceEdit.tsx
  client/src/zustand/artist.stores.ts
Labels: FE, Feat

#172 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
Labels: BE, Feat

#173 feat:review 예약안했는데 후기가 써지는 이슈 코드 수정
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/repository/ReservationRepository.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#177 feat: 예외 던지기 throw 추가
  BE/MainProject/src/main/java/com/codestates/performancereview/controller/ReviewController.java
  BE/MainProject/src/main/java/com/codestates/performancereview/service/ReviewService.java
  BE/MainProject/src/main/java/com/codestates/reservation/controller/ReservationController.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#178 Feat be/performance
  BE/MainProject/src/main/java/com/codestates/performance/entity/Performance.java
  BE/MainProject/src/main/java/com/codestates/performance/service/PerformanceServiceImpl.java
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#179 Fix: 마이페이지 예약에서 진행중인 공연과 완료된 공연이 반대로 나오는 이슈 수정
  BE/MainProject/src/main/java/com/codestates/reservation/service/ReservationService.java
Labels: BE, Feat

#180 Feat fe/refactor
  client/public/dummy/main_artistlist.json
  client/public/dummy/main_perfomancelist.json
  client/src/components/artist/ArtistHome.styled.ts
  client/src/components/artist/ArtistHome.tsx
  client/src/components/carousel/CarouselLogic.tsx
  client/src/components/carousel/CarouselSlide.styled.ts
  client/src/components/carousel/CarouselSlide.tsx
  client/src/images/pexels-emre-akyol-16822720.jpg
  client/src/images/pexels-monica-silvestre-713149.jpg
  client/src/images/pexels-nothing-ahead-9494909.jpg
  client/src/images/pexels-ricardo-rojas-3608804.jpg
  client/src/index.tsx
  client/src/model/Artist.ts
  client/src/pages/home/Home.tsx
  client/src/pages/sign/SignIn.tsx
  client/src/pages/sign/SignUp.tsx
Labels: FE

#181 Feat fe/refactor
  client/public/Images/pexels-cottonbro-studio-6853287.jpg
  client/public/Images/단체사진.jpg
  client/public/Images/여성사진.jpg
  client/public/Images/여성사진2.jpg
  client/public/Images/여성사진3.jpg
  client/public/Images/피아노.webp
  client/src/components/slogan/Slogan.tsx
  client/src/images/7955f4c5e4d540fb.png
  client/src/images/dd28119305b114d0.png
Labels: FE

#182 Feat fe/pages
  client/src/api/fetchAPI.ts
  client/src/api/useFetch.ts
  client/src/components/buttons/Buttons.style.ts
  client/src/components/inputs/Inputs.style.ts
  client/src/components/inputs/editor/Editor.tsx
  client/src/components/modal/Reservation.tsx
  client/src/components/modal/ReservationTicket.tsx
  client/src/components/modal/Ticket.tsx
  client/src/components/modal/review-info/ReviewInfo.style.ts
  client/src/components/modal/review-info/ReviewInfo.tsx
  client/src/components/modal/review-register/ReviewRegister.tsx
  client/src/components/reservation-preview/ReservationPreview.tsx
  client/src/components/review/Review.tsx
  client/src/model/Member.ts
  client/src/model/Reservation.ts
  client/src/pages/artist-list/ArtistList.style.ts
  client/src/pages/artist-list/ArtistList.tsx
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/mypage/EditMyPage.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/performance-list/PerformanceList.style.ts
  client/src/pages/performance/Performance.styled.ts
  client/src/pages/performance/performance-edit/PerformanceEdit.tsx
  client/src/pages/performance/performance-info/PerformanceInfo.style.ts
  client/src/pages/performance/performance-info/PerformanceInfo.tsx
Labels: FE, Feat

#187 Feat fe/responsive
  client/src/components/header/Header.tsx
  client/src/components/modal/Reservation.tsx
  client/src/components/modal/Ticket.style.ts
  client/src/components/modal/review-register/ReviewRegister.style.ts
  client/src/components/reservation-preview/ReservationPreview.tsx
  client/src/components/review/Review.tsx
  client/src/pages/cancel/Cancel.styled.ts
  client/src/pages/mypage/EditMyPage.style.ts
  client/src/pages/performance-register/PerformanceRegister.style.ts
  client/src/pages/performance/performance-info/PerformanceInfo.style.ts
Labels: FE

#191 Fix fe/feedback
  README.md
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/src/components/inputs/editor/Editor.style.tsx
  client/src/components/modal/review-register/ReviewRegister.style.ts
  client/src/components/modal/review/review-edit/ReviewEdit.tsx
  client/src/components/modal/review/review-info/ReviewInfo.style.ts
  client/src/pages/artist-list/ArtistList.style.ts
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist-register/ArtistRegister.style.ts
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/performance-register/PerformanceRegister.style.ts
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/performance/performance-edit/PerformanceEdit.tsx
  client/src/pages/performance/performance-info/PerformanceInfo.tsx
  client/src/utils/Filter.ts
Labels: bug, FE, Feat

#192 Fix fe/improve
  client/src/pages/home/Home.tsx
  client/src/pages/mypage/MyPage.tsx
Labels: bug, FE

#193 Fix fe/feedback
  client/src/pages/artist-list/ArtistList.tsx
  client/src/pages/artist-register/ArtistEdit.tsx
  client/src/pages/artist-register/ArtistRegister.tsx
  client/src/pages/mypage/EditMyPage.tsx
  client/src/pages/performance-register/PerformanceRegister.style.ts
  client/src/pages/performance-register/PerformanceRegister.tsx
  client/src/pages/performance/performance-info/PerformanceInfo.tsx
  client/src/utils/Category.ts
Labels: bug, FE

#194 Feat fe/member
  client/src/api/fetchAPI.ts
  client/src/pages/sign/SignIn.tsx
Labels: FE, Feat

#196 Style: 공연 정보 페이지 포스터 테두리 수정
  client/src/pages/performance/performance-info/PerformanceInfo.style.ts
Labels: FE

#197 Fix: 아티스트 페이지
  client/src/pages/artist/Artist.tsx
Labels: bug, FE, Feat
